<a href="https://colab.research.google.com/github/palakdawra4/BigDataAnalysis/blob/main/labeval_group2_2023010141.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
arr1 = np.array([10, 52, 62, 16, 16, 54,453])
print(np.sort(arr1))
indices=np.argsort(arr1)
print(indices)
a=4
small=np.sort(arr1[:a])
print(small)
n=5
rslt = arr1[-n : ]
print(rslt)



[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 52 62]
[ 62  16  16  54 453]
