<a href="https://colab.research.google.com/github/palakdawra4/BigDataAnalysis/blob/main/labeval_group2_2023010141.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
arr1 = np.array([10, 52, 62, 16, 16, 54,453])
data=np.sort(arr1)
print(data)
indices=np.argsort(arr1)
print(indices)
print(data[:4])
print(data[-5 : ])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]
